# -*- coding: utf-8 -*-
"""Tabla mundial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tY5HR-w0CuGaUa7JRjAAZJg5u8-rUf-A
"""



"""### World Cup Score Tracker and Leaderboard

This setup allows you to input daily match results, calculate points for each member based on their predictions, and display a cumulative leaderboard.
"""

import pandas as pd

# Define the members
members = ['Emi', 'Richi', 'Mido', 'Vivi', 'Jorge', 'Rocio', 'Ricardo']

"""#### Scoring Rules:
- **12 points**: Exact score predicted (e.g., predicted 2-1, actual 2-1).
- **5 points**: Correct outcome predicted (e.g., predicted Team A win, Team A wins, but score is 3-0 not 2-1).

Let's define a function to calculate points for a single match.
"""

def calculate_points(prediction_home, prediction_away, actual_home, actual_away):
    points = 0
    # Check for exact score
    if prediction_home == actual_home and prediction_away == actual_away:
        points = 12
    else:
        # Determine outcome for prediction
        pred_outcome = 'win_home' if prediction_home > prediction_away \
                       else ('win_away' if prediction_home < prediction_away else 'draw')

        # Determine outcome for actual result
        actual_outcome = 'win_home' if actual_home > actual_away \
                         else ('win_away' if actual_home < actual_away else 'draw')

        # Check for correct outcome
        if pred_outcome == actual_outcome:
            points = 5
    return points

"""Now, let's set up our initial leaderboard. We'll also create a function to add match results and update the scores for all members."""

# Initialize the leaderboard
leaderboard_df = pd.DataFrame({'Member': members, 'Total Points': [0] * len(members)})
leaderboard_df = leaderboard_df.set_index('Member')

# Store all match predictions and actual results
match_data = []

def add_match_results(match_name, actual_score_home, actual_score_away, predictions):
    """
    Adds a new match result and updates the leaderboard.

    Args:
        match_name (str): Name of the match (e.g., 'Brazil vs Germany').
        actual_score_home (int): Actual goals for the home team.
        actual_score_away (int): Actual goals for the away team.
        predictions (dict): Dictionary where keys are member names and values are
                            tuples (pred_home, pred_away) for their score prediction.
    """
    global leaderboard_df, match_data

    match_info = {'Match': match_name, 'Actual Score': f'{actual_score_home}-{actual_score_away}'}

    current_match_points = {}
    for member in members:
        pred_home, pred_away = predictions.get(member, (None, None))
        if pred_home is not None and pred_away is not None:
            points = calculate_points(pred_home, pred_away, actual_score_home, actual_score_away)
            leaderboard_df.loc[member, 'Total Points'] += points
            current_match_points[member] = points
            match_info[f'{member} Prediction'] = f'{pred_home}-{pred_away}'
            match_info[f'{member} Points'] = points
        else:
            current_match_points[member] = 0
            match_info[f'{member} Prediction'] = 'N/A'
            match_info[f'{member} Points'] = 0

    match_data.append(match_info)
    print(f"\n--- Results for {match_name} ---")
    for member, points in current_match_points.items():
        print(f"{member}: +{points} points")

    print("\nUpdated Leaderboard:")
    display(leaderboard_df.sort_values(by='Total Points', ascending=False))

# Display initial leaderboard
print("Initial Leaderboard:")
display(leaderboard_df.sort_values(by='Total Points', ascending=False))

"""#### Example Usage:

Let's simulate a day's matches. You will define the actual scores and each member's predictions for each match.
"""

# --- Day 1 Matches ---

# Match 1: Argentina vs. Saudi Arabia
match1_predictions = {
    'Emi': (2, 0),
    'Richi': (3, 1),
    'Mido': (2, 0),
    'Vivi': (1, 0),
    'Jorge': (4, 0),
    'Rocio': (2, 1),
    'Ricardo': (3, 0)
}
add_match_results('Argentina vs. Saudi Arabia', actual_score_home=1, actual_score_away=2, predictions=match1_predictions)

# Match 2: Germany vs. Japan
match2_predictions = {
    'Emi': (2, 1),
    'Richi': (1, 1),
    'Mido': (3, 0),
    'Vivi': (2, 0),
    'Jorge': (1, 0),
    'Rocio': (2, 2),
    'Ricardo': (2, 1)
}
add_match_results('Germany vs. Japan', actual_score_home=1, actual_score_away=2, predictions=match2_predictions)

# Match 3: Spain vs. Costa Rica
match3_predictions = {
    'Emi': (3, 0),
    'Richi': (2, 0),
    'Mido': (4, 0),
    'Vivi': (3, 1),
    'Jorge': (2, 0),
    'Rocio': (5, 0),
    'Ricardo': (3, 0)
}
add_match_results('Spain vs. Costa Rica', actual_score_home=7, actual_score_away=0, predictions=match3_predictions)

"""You can continue to add more matches by calling `add_match_results()` with the respective match name, actual scores, and each member's predictions. The leaderboard will automatically update and display the current rankings after each match."""

# To see all match results and predictions:
# pd.DataFrame(match_data)